language: node_js
node_js:
- "8"
addons:
  ssh_known_hosts:
  - bitesized.xyz
before_install:
- openssl aes-256-cbc -K $encrypted_f23b4cb21e5c_key -iv $encrypted_f23b4cb21e5c_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
before_script:
- chmod +x ./.travis/deploy.sh
script: "./.travis/deploy.sh"
